# Generated by Django 5.1.1 on 2024-10-16 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_feedback_email"),
        ("facultyapp", "0003_alter_addcourse_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("AOOP", "Advanced Object-Oriented Programming"),
                            ("PFSD", "Python Full Stack Development"),
                            ("AIML", "Artificial Intelligence and Machine Learning"),
                            ("LINUX", "Linux Administration"),
                            ("OS", "Operating Systems"),
                            ("MP", "Mathematical programming"),
                            ("DBMS", "Database Management Systems"),
                            ("MERN", "MERN Stack Development"),
                            ("CC", "Cloud Computing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("marks", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.studentlist",
                    ),
                ),
            ],
        ),
    ]
